# Generated by Django 5.2.8 on 2026-02-20 11:39

import django.db.models.deletion
import packages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_package_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadevent',
            name='package',
        ),
        migrations.RemoveField(
            model_name='package',
            name='archive',
        ),
        migrations.RemoveField(
            model_name='package',
            name='readme',
        ),
        migrations.RemoveField(
            model_name='package',
            name='version',
        ),
        migrations.CreateModel(
            name='PackageVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=32, validators=[packages.models.validate_semver])),
                ('major', models.PositiveIntegerField(editable=False)),
                ('minor', models.PositiveIntegerField(editable=False)),
                ('patch', models.PositiveIntegerField(editable=False)),
                ('readme', models.TextField(blank=True)),
                ('archive', models.FileField(upload_to=packages.models.upload_to_package_version)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='packages.package')),
            ],
        ),
        migrations.AddField(
            model_name='downloadevent',
            name='version',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='packages.packageversion'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='packageversion',
            index=models.Index(fields=['package', '-major', '-minor', '-patch'], name='packages_pa_package_61d67c_idx'),
        ),
        migrations.AddConstraint(
            model_name='packageversion',
            constraint=models.UniqueConstraint(fields=('package', 'version'), name='uniq_package_version'),
        ),
    ]
