name: Django Tests

on:
  push:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GITHUB_CLIENT_ID: ${{ secrets.G_CLIENT_ID }}
      GITHUB_CLIENT_SECRET: ${{ secrets.G_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13.7

      - name: Set up virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate  # Activate the virtual environment

      - name: Install dependencies
        run: |
          source venv/bin/activate  # Ensure the venv is active
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage  # Install coverage tool

      - name: Run Django tests with coverage
        run: |
          source venv/bin/activate  # Activate the venv before running tests
          coverage run manage.py test  # Run tests with coverage
          coverage report  # Show coverage in the logs (optional)
          coverage xml -o coverage.xml  # Generate XML report for upload

      - name: Upload coverage to Codec
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: ColonyPM/cpm-repository
